version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: qrmenu-server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    container_name: qrmenu-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

# It does not work!
